name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_ENGINE_STRICT: 'false'
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm config set engine-strict false
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
      - name: Types-only check for test d.ts
        run: npx -y ts-node --compiler-options '{"allowImportingTsExtensions":true,"module":"esnext"}' --transpile-only tests/types.test-d.ts || true
      - run: npm test
      - run: npm run build


